### ISSUE TITLE
OT-cc2538 as RCP fails because of missing capabilities: tx-security tx-timing

### ISSUE THREAD

**Issue by Gunzter** [openthread/ot-cc2538#53]
I was trying to use the ot-cc2538 ot-rcp together with the ot-docker image.
I built commit 08e58f0d6cd17144fe6e5c36d731233c780a2331 with commands:
`./script/bootstrap`
`./script/build`
`arm-none-eabi-objcopy -O binary build/bin/ot-rcp build/bin/ot-rcp.bin`
`python3 $HOME/workspace/cc2538-bsl/cc2538-bsl.py -e -w -v -p "/dev/ttyACM0" -a 0x00200000  build/bin/ot-rcp.bin`

Then I start the docker image with:
`docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8080:80 --dns=127.0.0.1 -it --volume /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr --radio-url spinel+hdlc+uart:///dev/ttyACM0'

> May 26 09:17:16 19e50772afcd avahi-daemon[186]: New relevant interface eth0.IPv4 for mDNS.
May 26 09:17:16 19e50772afcd avahi-daemon[186]: Joining mDNS multicast group on interface lo.IPv6 with address ::1.
May 26 09:17:16 19e50772afcd avahi-daemon[186]: New relevant interface lo.IPv6 for mDNS.
May 26 09:17:16 19e50772afcd avahi-daemon[186]: Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
May 26 09:17:16 19e50772afcd avahi-daemon[186]: New relevant interface lo.IPv4 for mDNS.
May 26 09:17:16 19e50772afcd avahi-daemon[186]: Network interface enumeration completed.
May 26 09:17:16 19e50772afcd avahi-daemon[186]: Registering new address record for fe80::42:acff:fe11:2 on eth0.*.
May 26 09:17:16 19e50772afcd avahi-daemon[186]: Registering new address record for 172.17.0.2 on eth0.IPv4.
May 26 09:17:16 19e50772afcd avahi-daemon[186]: Registering new address record for ::1 on lo.*.
May 26 09:17:16 19e50772afcd avahi-daemon[186]: Registering new address record for 127.0.0.1 on lo.IPv4.
May 26 09:17:17 19e50772afcd otbr-agent[214]: [INFO]-UTILS---: Running 0.3.0
May 26 09:17:17 19e50772afcd otbr-agent[214]: [INFO]-UTILS---: Thread version: 1.2.0
May 26 09:17:17 19e50772afcd otbr-agent[214]: [INFO]-UTILS---: Thread interface: wpan0
May 26 09:17:17 19e50772afcd otbr-agent[214]: [INFO]-UTILS---: Backbone interface: eth0
May 26 09:17:17 19e50772afcd otbr-agent[214]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
May 26 09:17:17 19e50772afcd otbr-agent[214]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
May 26 09:17:17 19e50772afcd otbr-web[242]: [INFO]-WEB-----: Running 0.3.0
May 26 09:17:17 19e50772afcd otbr-web[242]: [INFO]-WEB-----: Border router web started on wpan0
May 26 09:17:17 19e50772afcd otbr-web[242]: [ERR ]-WEB-----: OpenThread daemon is not running.
May 26 09:17:17 19e50772afcd otbr-agent[214]: [NOTE]-PLAT----: RCP API Version: 3
May 26 09:17:17 19e50772afcd otbr-agent[214]: [CRIT]-PLAT----: RCP is missing required capabilities: tx-security tx-timing 
May 26 09:17:17 19e50772afcd otbr-agent[214]: [CRIT]-PLAT----: CheckRadioCapabilities() at ../../third_party/openthread/repo/src/lib/spinel/radio_spinel_impl.hpp:384: RadioSpinelIncompatible

As I have seen from other OT issues and questions on mailing lists, there seem to be an upgrade of the Thread Protocol version to 1.2, is that the culprit here also?

**Comment by jwhui** [comment]
@Gunzter , yes, we do not currently have required Thread 1.2 features supported on the CC2538.

To use OTBR in Thread 1.1 mode you try adding the following line to [third_party/openthread/CMakeLists.txt](https://github.com/openthread/ot-br-posix/blob/main/third_party/openthread/CMakeLists.txt)
```
set(OT_THREAD_VERSION 1.1 CACHE STRING "Thread 1.1" FORCE)
```

Then make sure to set `BACKBONE_ROUTER=0` when invoking `./script/setup`
```
BACKBONE_ROUTER=0 ./script/setup
```

Hope that helps.

**Comment by Gunzter** [comment]
Hi,
I added: `set(OT_THREAD_VERSION 1.1 CACHE STRING "Thread 1.1" FORCE)` to line 40 of `third_party/openthread/CMakeLists.txt`

I also changed line 89 in `etc/docker/Dockerfile` from `&& ./script/setup \ ` to `&& BACKBONE_ROUTER=0 ./script/setup \`

That solved the problem! Thank you!

I will close the issue.

**Comment by dougleaf** [comment]
For some reason I'm trying to do the same thing (made the same changes as you @Gunzter), but I still see prints of both `OPENTHREAD_CONFIG_THREAD_VERSION=OT_THREAD_VERSION_1_2` and `OPENTHREAD_CONFIG_BACKBONE_ROUTER_ENABLE=1` while building

@AliakbarEski @jwhui

**Comment by dougleaf** [comment]
Update: it worked after deleting the whole CMake build folder @jwhui
